


{
 "resultCount":1,
 "results": [
{"isGameCenterEnabled":false, "ipadScreenshotUrls":[], "appletvScreenshotUrls":[], "artworkUrl60":"http://is2.mzstatic.com/image/thumb/Purple118/v4/ef/45/13/ef451355-1d47-aa52-15d1-b149eba4f53f/source/60x60bb.jpg", "artworkUrl512":"http://is2.mzstatic.com/image/thumb/Purple118/v4/ef/45/13/ef451355-1d47-aa52-15d1-b149eba4f53f/source/512x512bb.jpg", "artworkUrl100":"http://is2.mzstatic.com/image/thumb/Purple118/v4/ef/45/13/ef451355-1d47-aa52-15d1-b149eba4f53f/source/100x100bb.jpg", "artistViewUrl":"https://itunes.apple.com/us/developer/bank-cimb-niaga-tbk/id425193419?uo=4", 
"screenshotUrls":["http://is3.mzstatic.com/image/thumb/Purple128/v4/dc/56/b3/dc56b353-b8a0-60ba-504f-510479fd9a6d/source/392x696bb.jpg", "http://is3.mzstatic.com/image/thumb/Purple118/v4/fe/ba/4c/feba4c86-f986-ab69-a88b-f68ce11c1008/source/392x696bb.jpg", "http://is3.mzstatic.com/image/thumb/Purple128/v4/6f/e2/d3/6fe2d3d2-69b4-4ad4-f3bf-ad9933ab9519/source/392x696bb.jpg", "http://is5.mzstatic.com/image/thumb/Purple118/v4/70/9a/f4/709af4ad-b810-d509-dec3-c782bb3f697d/source/392x696bb.jpg"], "kind":"software", "features":[], "advisories":[], 
"supportedDevices":["iPhone4-iPhone4", "iPad2Wifi-iPad2Wifi", "iPad23G-iPad23G", "iPhone4S-iPhone4S", "iPadThirdGen-iPadThirdGen", "iPadThirdGen4G-iPadThirdGen4G", "iPhone5-iPhone5", "iPodTouchFifthGen-iPodTouchFifthGen", "iPadFourthGen-iPadFourthGen", "iPadFourthGen4G-iPadFourthGen4G", "iPadMini-iPadMini", "iPadMini4G-iPadMini4G", "iPhone5c-iPhone5c", "iPhone5s-iPhone5s", "iPadAir-iPadAir", "iPadAirCellular-iPadAirCellular", "iPadMiniRetina-iPadMiniRetina", "iPadMiniRetinaCellular-iPadMiniRetinaCellular", "iPhone6-iPhone6", "iPhone6Plus-iPhone6Plus", "iPadAir2-iPadAir2", "iPadAir2Cellular-iPadAir2Cellular", "iPadMini3-iPadMini3", "iPadMini3Cellular-iPadMini3Cellular", "iPodTouchSixthGen-iPodTouchSixthGen", "iPhone6s-iPhone6s", "iPhone6sPlus-iPhone6sPlus", "iPadMini4-iPadMini4", "iPadMini4Cellular-iPadMini4Cellular", "iPadPro-iPadPro", "iPadProCellular-iPadProCellular", "iPadPro97-iPadPro97", "iPadPro97Cellular-iPadPro97Cellular", "iPhoneSE-iPhoneSE", "iPhone7-iPhone7", "iPhone7Plus-iPhone7Plus", "iPad611-iPad611", "iPad612-iPad612", "iPad71-iPad71", "iPad72-iPad72", "iPad73-iPad73", "iPad74-iPad74", "iPhone8-iPhone8", "iPhone8Plus-iPhone8Plus", "iPhoneX-iPhoneX"], "averageUserRatingForCurrentVersion":4.0, "trackCensoredName":"Go Mobile by CIMB Niaga", "languageCodesISO2A":["EN", "ID"], "fileSizeBytes":"42077184", "sellerUrl":"http://www.cimbniaga.com", "contentAdvisoryRating":"4+", "userRatingCountForCurrentVersion":1, "trackViewUrl":"https://itunes.apple.com/us/app/go-mobile-by-cimb-niaga/id505917174?mt=8&uo=4", "trackContentRating":"4+", "formattedPrice":"Free", "minimumOsVersion":"7.0", "currency":"USD", "wrapperType":"software", "version":"2.0.3", "artistId":425193419, "artistName":"Bank CIMB Niaga Tbk", "genres":["Finance", "Lifestyle"], "price":0.00, 
"description":"Hooray! \n\nSay hello to the new Go Mobile! \n\nWhat’s new in the new Go Mobile?\nLook and feel: new design with day and night wallpaper.\nLogin experience: login using fingerprint feature, 1 device login for secure transaction\nShare transaction proof: now you can share your transaction proof via Whatsapp, SMS, or email\nPromo code: you can enter eligible promo code to join Bank promo with interesting reward\nRekening Ponsel online registration\nEnhanced Favorites List: manage your favorite list easier\nMaintenance: now you can set your preferred notification method – SMS or application\n\nBanking features at your fingertips with Go Mobile:\n1. Balance information on all your accounts with CIMB Niaga.\n2. View transaction history of your savings, Rekening Ponsel and credit card account\n3. Bill payments: credit cards (issued by Indonesian banks), personal loan, insurance, phone bills, etc\n4. Mobile airtime reload\n5. Rekening Ponsel transactions & purchases\n6. Money transfers:  any bank accounts in Indonesia & overseas, Rekening Ponsel (mobile wallet) in real time or by clearing.\n7. Account maintenance:  favorite payment & transfer list, PIN and User ID change, set default account\n8. Access to your photo library and camera is required to update your photo profile.\n9. Access to your camera is required to access AR mode.\n10. Find nearest CIMB Niaga ATM, branch, and Digital Lounge locations\n\nDOWNLOAD now to start using Go Mobile!\n\nImportant note:\n1. ONLY register your OWN mobile number to use Go Mobile.\n2. ALWAYS keep your PASSCODE and PIN confidential. It is a secure code to authorize your financial transactions. Go Mobile will not ask for your PIN for any other reasons.\n3. GO MOBILE is FREE of charge. All applicable SMS fees are directly charged by Telecommunication Companies to your phone bill or deducted from your prepaid airtime.     \n\n\nWhen you don’t have access to data plan, you can dial *141*8# to access Go Mobile. \nFor further information & assistance, please contact 14041 or 14041@cimbniaga.co.id. \n\nSave time and do more with Go Mobile.", "bundleId":"com.cimbniaga.CIMB", "genreIds":["6015", "6012"], "currentVersionReleaseDate":"2018-02-02T17:43:26Z", "primaryGenreName":"Finance", "isVppDeviceBasedLicensingEnabled":true, "releaseDate":"2012-03-19T16:20:21Z", "primaryGenreId":6015, "sellerName":"Bank CIMB Niaga Tbk", 
"releaseNotes":"New month, new update!\n\nWe are constantly updating the apps to ease your banking transaction. This new update include RTGS transfer and performance enhancement improvement.\n\nEnjoy Go Mobile, cheers!", "trackId":505917174, "trackName":"Go Mobile by CIMB Niaga", "averageUserRating":2.0, "userRatingCount":28}]
}


